# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 21:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(upload_to='Images/')),
                ('company_name', models.TextField(max_length=255)),
                ('company_url', models.URLField()),
                ('company_email', models.EmailField(max_length=254)),
                ('company_mobile', models.IntegerField()),
                ('company_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
