# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20170614_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='company_name_image',
            field=models.ImageField(blank=True, null=True, upload_to='Images/Pics'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='company_name',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
