# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20170614_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='Images/'),
        ),
    ]
